"""Generates engine/src/game/ram.h: named RAM addresses (from the reference
disassembly's symbols) plus typed views of the game's RAM structures."""
import os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import analyze

ROOT = analyze.ROOT


def main():
    defs = {}
    sizes = {}
    section = None
    for line in open(analyze.REF_SYM):
        line = line.strip()
        if line.startswith("["):
            section = line
            continue
        if section != "[definitions]" or not line or line.startswith(";"):
            continue
        val, name = line.split(None, 1)
        val = int(val, 16)
        if name.startswith("_sizeof_"):
            sizes[name[8:]] = val
        elif 0xC000 <= val <= 0xDFFF and "." not in name and re.match(r"^[A-Za-z_]\w*$", name):
            defs[name] = val
    out = [
        "/* Generated by engine/recomp/gen_ram.py from the reference disassembly. Do not edit. */",
        "#ifndef GAME_RAM_H",
        "#define GAME_RAM_H",
        "",
        "#include <stdint.h>",
        "",
        '#include "rt/cpu.h"',
        "",
        "/* Unaligned little-endian 16-bit view of RAM. */",
        "typedef struct __attribute__((packed)) RamWord { uint16_t v; } RamWord;",
        "",
        "#define ram8(addr) (mach.ram[(uint16_t)(addr) - 0xC000])",
        "#define ram16(addr) (((RamWord *)&mach.ram[(uint16_t)(addr) - 0xC000])->v)",
        "#define ram_ptr(addr) (&mach.ram[(uint16_t)(addr) - 0xC000])",
        "",
        "/* Game object slot (32 bytes). $C300 is Alex, then 29 more slots. */",
        "typedef struct __attribute__((packed)) Entity {",
        "    uint8_t type;                    /* +00 updater index, 0 = free */",
        "    uint8_t flags;                   /* +01 */",
        "    uint8_t unknown1;                /* +02 */",
        "    uint8_t data;                    /* +03 */",
        "    uint8_t animationFrame;          /* +04 */",
        "    uint8_t animationTimer;          /* +05 */",
        "    uint8_t animationTimerResetValue;/* +06 */",
        "    uint16_t spriteDescriptorPointer;/* +07 */",
        "    uint16_t isOffScreenFlags;       /* +09 */",
        "    uint16_t xPos;                   /* +0B 8.8 fixed point, high byte = pixel */",
        "    uint16_t yPos;                   /* +0D */",
        "    uint16_t xSpeed;                 /* +0F */",
        "    uint16_t ySpeed;                 /* +11 */",
        "    uint8_t unknown2;                /* +13 */",
        "    uint8_t unknown3;                /* +14 */",
        "    uint8_t unknown4;                /* +15 */",
        "    uint8_t unknown5;                /* +16 */",
        "    uint8_t battleDecision;          /* +17 */",
        "    uint8_t unknown6;                /* +18 */",
        "    uint8_t unknown7;                /* +19 */",
        "    uint8_t state;                   /* +1A */",
        "    uint8_t stateTimer;              /* +1B */",
        "    uint8_t unknown8;                /* +1C */",
        "    uint8_t unknown9;                /* +1D */",
        "    uint8_t unknown10;               /* +1E */",
        "    uint8_t unknown11;               /* +1F */",
        "} Entity;",
        "_Static_assert(sizeof(Entity) == 32, \"Entity layout\");",
        "#define entity_at(addr) ((Entity *)ram_ptr(addr))",
        "",
        "/* Sound engine software channel (32 bytes). */",
        "typedef struct __attribute__((packed)) SoftwareChannel {",
        "    uint8_t flags;",
        "    uint8_t hardwareChannel;",
        "    uint8_t duration;",
        "    uint16_t dataPointer;",
        "    uint8_t transpose;",
        "    uint8_t pitchEnvelope;",
        "    uint8_t volumeEnvelope;",
        "    uint8_t volume;",
        "    uint8_t unknown1;",
        "    uint16_t noteDuration;",
        "    uint16_t currentPlayDuration;",
        "    uint8_t volumeEnvelopeCounter;",
        "    uint8_t pitchEnvelopeCounter;",
        "    uint16_t noteFrequency;",
        "    uint16_t frequencyToWrite;",
        "    uint16_t noteFrequency2;",
        "    uint8_t volumeToWrite;",
        "    uint8_t repetitionCounters[9];",
        "} SoftwareChannel;",
        "_Static_assert(sizeof(SoftwareChannel) == 32, \"SoftwareChannel layout\");",
        "#define channel_at(addr) ((SoftwareChannel *)ram_ptr(addr))",
        "",
        "/* Named RAM variables (address; size in bytes). */",
        "enum {",
    ]
    for name, addr in sorted(defs.items(), key=lambda kv: (kv[1], kv[0])):
        sz = sizes.get(name)
        out.append("    %-52s = 0x%04X,%s" % (name, addr, (" /* %d bytes */" % sz) if sz and sz > 2 else ""))
    out += ["};", "", "#endif", ""]
    path = os.path.join(ROOT, "engine", "src", "game", "ram.h")
    open(path, "w").write("\n".join(out))
    print("%d RAM names -> %s" % (len(defs), path))


if __name__ == "__main__":
    main()
