/* Generated by engine/recomp/gen_ram.py from the reference disassembly. Do not edit. */
#ifndef GAME_RAM_H
#define GAME_RAM_H

#include <stdint.h>

#include "rt/cpu.h"

/* Unaligned little-endian 16-bit view of RAM. */
typedef struct __attribute__((packed)) RamWord { uint16_t v; } RamWord;

#define ram8(addr) (mach.ram[(uint16_t)(addr) - 0xC000])
#define ram16(addr) (((RamWord *)&mach.ram[(uint16_t)(addr) - 0xC000])->v)
#define ram_ptr(addr) (&mach.ram[(uint16_t)(addr) - 0xC000])

/* Game object slot (32 bytes). $C300 is Alex, then 29 more slots. */
typedef struct __attribute__((packed)) Entity {
    uint8_t type;                    /* +00 updater index, 0 = free */
    uint8_t flags;                   /* +01 */
    uint8_t unknown1;                /* +02 */
    uint8_t data;                    /* +03 */
    uint8_t animationFrame;          /* +04 */
    uint8_t animationTimer;          /* +05 */
    uint8_t animationTimerResetValue;/* +06 */
    uint16_t spriteDescriptorPointer;/* +07 */
    uint16_t isOffScreenFlags;       /* +09 */
    uint16_t xPos;                   /* +0B 8.8 fixed point, high byte = pixel */
    uint16_t yPos;                   /* +0D */
    uint16_t xSpeed;                 /* +0F */
    uint16_t ySpeed;                 /* +11 */
    uint8_t unknown2;                /* +13 */
    uint8_t unknown3;                /* +14 */
    uint8_t unknown4;                /* +15 */
    uint8_t unknown5;                /* +16 */
    uint8_t battleDecision;          /* +17 */
    uint8_t unknown6;                /* +18 */
    uint8_t unknown7;                /* +19 */
    uint8_t state;                   /* +1A */
    uint8_t stateTimer;              /* +1B */
    uint8_t unknown8;                /* +1C */
    uint8_t unknown9;                /* +1D */
    uint8_t unknown10;               /* +1E */
    uint8_t unknown11;               /* +1F */
} Entity;
_Static_assert(sizeof(Entity) == 32, "Entity layout");
#define entity_at(addr) ((Entity *)ram_ptr(addr))

/* Sound engine software channel (32 bytes). */
typedef struct __attribute__((packed)) SoftwareChannel {
    uint8_t flags;
    uint8_t hardwareChannel;
    uint8_t duration;
    uint16_t dataPointer;
    uint8_t transpose;
    uint8_t pitchEnvelope;
    uint8_t volumeEnvelope;
    uint8_t volume;
    uint8_t unknown1;
    uint16_t noteDuration;
    uint16_t currentPlayDuration;
    uint8_t volumeEnvelopeCounter;
    uint8_t pitchEnvelopeCounter;
    uint16_t noteFrequency;
    uint16_t frequencyToWrite;
    uint16_t noteFrequency2;
    uint8_t volumeToWrite;
    uint8_t repetitionCounters[9];
} SoftwareChannel;
_Static_assert(sizeof(SoftwareChannel) == 32, "SoftwareChannel layout");
#define channel_at(addr) ((SoftwareChannel *)ram_ptr(addr))

/* Named RAM variables (address; size in bytes). */
enum {
    v_highScore                                          = 0xC000, /* 4 bytes */
    v_VDPRegister1Value                                  = 0xC004,
    v_inputFlags                                         = 0xC005,
    v_inputData                                          = 0xC006,
    v_inputDataChanges                                   = 0xC007,
    v_interruptFlags                                     = 0xC008,
    v_spriteTerminatorPointer                            = 0xC009,
    paletteUpdaterPointer                                = 0xC00E,
    v_textBoxMessageIndex                                = 0xC011,
    _RAM_C014_                                           = 0xC014,
    v_disallowMap                                        = 0xC015,
    v_nextDemoIndex                                      = 0xC016,
    v_gameState                                          = 0xC01F,
    v_score                                              = 0xC020, /* 3 bytes */
    v_level                                              = 0xC023,
    v_lives                                              = 0xC025,
    v_money                                              = 0xC030,
    v_moneyByteTwo                                       = 0xC031,
    v_currentMapOrTextNametablePointer                   = 0xC038,
    v_currentMapNametableDestinationPointer              = 0xC03A,
    v_mapLoadingState                                    = 0xC03C,
    v_shouldUpdateMapNametable                           = 0xC03D,
    v_nextMapNametableUpdateTimer                        = 0xC03E,
    v_levelStartingTimer                                 = 0xC03F,
    v_hasMagicCapsuleA                                   = 0xC046,
    v_hasMagicCapsuleB                                   = 0xC047,
    v_hasTelepathyBall                                   = 0xC048,
    v_hasCaneOfFlight                                    = 0xC049,
    v_hasTeleportPowder                                  = 0xC04A,
    v_hasMoonstoneMedallion                              = 0xC04B,
    v_hasLetterToNibana                                  = 0xC04C,
    v_hasPowerBracelet                                   = 0xC04D,
    v_hasHirottaStone                                    = 0xC04E,
    v_hasSunstoneMedallion                               = 0xC04F,
    v_shouldSpawnRidingBoat_RAM_C051_                    = 0xC051,
    v_inventoryItemSelectionState                        = 0xC053,
    v_alexActionState                                    = 0xC054,
    v_shopFlags                                          = 0xC055,
    v_shopSelectedItemIndex                              = 0xC056,
    v_itemBeignBoughtIndex                               = 0xC057,
    v_selectedItemNametablePointer                       = 0xC058,
    v_invincibilityTimer                                 = 0xC05A,
    v_shouldBlankLeftmostColumn                          = 0xC05C,
    v_invincibilityColorTimer                            = 0xC05D,
    v_VDPRegister0Value                                  = 0xC05F,
    v_entityDescriptorsPointer                           = 0xC061,
    v_addedEntitiesShouldBeOffscreenHorizontally         = 0xC063,
    v_addedEntitiesShouldBeOffscreenVertically           = 0xC064,
    v_entityIndex                                        = 0xC065,
    v_isScrollingDownToNextScreen                        = 0xC066,
    v_newEntityVerticalOffset                            = 0xC067,
    v_shopDoorOffset                                     = 0xC069,
    v_shopEntranceDoorNametablePointer                   = 0xC06A,
    v_horizontalPositionShopHasBeenEnteredFrom           = 0xC06C,
    v_shopEntranceEnteredFromDoorNametablePointer        = 0xC06D,
    v_shouldAlexStartWalkingtoNextScreen                 = 0xC06F,
    v_nuraiOrOldManEntityTemporaryPointer                = 0xC070,
    v_nuraiOrOldManEntityAnimationDescriptorTemporaryPointer = 0xC072,
    _RAM_C074_                                           = 0xC074,
    v_shouldShowNuraiOrOldMan                            = 0xC076,
    v_specialLevelScrollFlags                            = 0xC077,
    targetBase_RAM_C07A_                                 = 0xC078,
    targetBlock_RAM_C07A_                                = 0xC07A,
    v_questionMarkBoxIndex                               = 0xC07C,
    v_textBoxCounter                                     = 0xC07D,
    v_textBoxFlags                                       = 0xC07E,
    _RAM_C07F_                                           = 0xC07F,
    v_levelScrollFlags                                   = 0xC080,
    v_levelBankNumber                                    = 0xC081,
    scrollFlagsUpdaterPointer                            = 0xC085,
    v_metatileNametablePointer                           = 0xC087,
    v_entityLoaderPointer                                = 0xC089,
    v_currentScreenNumber                                = 0xC08D,
    _RAM_C08E_                                           = 0xC08E,
    v_powerBraceletsPickedUpCounter                      = 0xC08F,
    v_alexStateBeforeHit                                 = 0xC090,
    v_newEntityHorizontalOffset                          = 0xC091,
    v_currentLevelIsBonusLevel                           = 0xC092,
    v_shouldOpenMap                                      = 0xC093,
    v_endingSequencePointer                              = 0xC094,
    _RAM_C095_                                           = 0xC095,
    v_resetButtonState                                   = 0xC096,
    v_levelWidth                                         = 0xC0A0,
    v_linesToLoadToNametable                             = 0xC0A1,
    v_levelData_C0A2                                     = 0xC0A2,
    v_levelLayoutPointer                                 = 0xC0A3,
    v_levelHeight                                        = 0xC0A5,
    v_columnsToLoadToNametable                           = 0xC0A6,
    v_levelData_C0A7                                     = 0xC0A7,
    v_SecondLevelLayoutPointer                           = 0xC0A8,
    v_UpdateNameTableFlags                               = 0xC0AA,
    v_horizontalScrollSpeed                              = 0xC0AB,
    v_horizontalScrollAccumulator                        = 0xC0AD,
    v_horizontalScroll                                   = 0xC0AF,
    v_levelData_C0B0                                     = 0xC0B0,
    v_levelData_C0B2                                     = 0xC0B2,
    v_levelData_C0B3_                                    = 0xC0B3,
    v_levelData_C0B4_                                    = 0xC0B4,
    v_levelData_C0B5_                                    = 0xC0B5,
    v_horizontalScreenNumber                             = 0xC0B6,
    v_levelData_C0B7_                                    = 0xC0B7,
    v_verticalScrollSpeed                                = 0xC0B9,
    v_levelData_C0BA_                                    = 0xC0BA,
    v_levelData_C0BB_                                    = 0xC0BB,
    v_levelData_C0BC_                                    = 0xC0BC,
    v_verticalScroll                                     = 0xC0BD,
    v_levelData_C0BF                                     = 0xC0BF,
    v_levelData_C0C0                                     = 0xC0C0,
    v_levelData_C0C1_                                    = 0xC0C1,
    v_levelData_C0C2_                                    = 0xC0C2,
    v_levelData_C0C3_                                    = 0xC0C3,
    v_verticalScreenNumber                               = 0xC0C4,
    v_levelData_C0C5_                                    = 0xC0C5,
    v_levelData_C0C7                                     = 0xC0C7,
    v_levelData_C0C8                                     = 0xC0C8,
    v_scrollFlags                                        = 0xC0C9,
    v_temporaryLevelDataCopy                             = 0xC0CA, /* 42 bytes */
    _RAM_C0F4_                                           = 0xC0F4,
    v_entitydataArrayLength                              = 0xC0F8,
    v_entitydataArrayPointer                             = 0xC0F9,
    _RAM_C0FB_                                           = 0xC0FB,
    v_shopDoorNametablePointer                           = 0xC0FD,
    _RAM_C0FF_                                           = 0xC0FF,
    v_waterColorTimer                                    = 0xC100,
    v_introTimer                                         = 0xC103,
    v_demoInputDataPointer                               = 0xC105,
    v_demoCurrentInputData                               = 0xC107,
    v_nametableCopyFlags                                 = 0xC10A,
    v_1bppTileColor                                      = 0xC10B,
    v_spriteFlickeringCounter                            = 0xC10D,
    v_soundControl                                       = 0xC110,
    v_soundFadeOutVolume                                 = 0xC111,
    v_soundFadeOutTimer                                  = 0xC112,
    v_soundEffectPriority                                = 0xC113,
    v_soundSoftwareChannelSevenState                     = 0xC114,
    v_soundBattleSoundFlags                              = 0xC115,
    v_soundNumber                                        = 0xC116,
    v_soundMusicChannels                                 = 0xC118, /* 128 bytes */
    v_soundEffectsChannels                               = 0xC198, /* 96 bytes */
    v_alexTilesIndex                                     = 0xC200,
    v_nametableChangeRequest                             = 0xC202,
    _RAM_C203_                                           = 0xC203,
    v_nametableChangeDestination                         = 0xC204,
    nametableChangeSourceMetatile                        = 0xC206,
    _RAM_C208_                                           = 0xC208,
    _RAM_C209_                                           = 0xC209,
    _RAM_C20B_                                           = 0xC20B,
    v_alexHorizontalSpeedTemporaryCopy                   = 0xC20C,
    v_alexVerticalSpeedTemporaryCopy                     = 0xC20E,
    v_alexStateTemporaryCopy                             = 0xC210,
    _RAM_C211_                                           = 0xC211,
    v_nametableEntryAttrLastThreeBits                    = 0xC213,
    v_nextGhostSpawnTimer                                = 0xC214,
    v_hasBattleStarted                                   = 0xC215,
    v_hasBattleEnded                                     = 0xC216,
    v_BattleOpponentDecisionIndex                        = 0xC217,
    _RAM_C218_                                           = 0xC218,
    _RAM_C219_                                           = 0xC219,
    _RAM_C21B_                                           = 0xC21B,
    v_levelTileUpdateTimer                               = 0xC220,
    v_fourFrameLevelTileIndex                            = 0xC221,
    v_sixFrameLevelTileIndex                             = 0xC222,
    v_levelTileUpdaterPointer                            = 0xC223,
    v_shouldUpdateLevelTiles                             = 0xC225,
    v_titleScreenTimer                                   = 0xC226,
    v_currentTitleScreen                                 = 0xC227,
    v_titleScreenLogoTimer                               = 0xC228,
    _RAM_C229_                                           = 0xC229,
    _RAM_C22A_                                           = 0xC22A,
    v_battleOpponentSpriteDescriptorPointer              = 0xC230,
    v_battleOpponentTilesPointer                         = 0xC232,
    v_opponentNamePointer                                = 0xC234,
    v_opponentAnimationDescriptorPointer                 = 0xC236,
    v_opponentCountdownAnimationDescriptorPointer        = 0xC238,
    v_opponentThrowSpriteDescriptorPointer               = 0xC23A,
    v_opponentDecisionsPointer                           = 0xC23C,
    v_battleOpponentMessagePointer                       = 0xC23E,
    temporaryAlexCopy                                    = 0xC240, /* 26 bytes */
    _RAM_C25A_                                           = 0xC25A,
    _RAM_C25C_                                           = 0xC25C,
    _RAM_C260_                                           = 0xC260, /* 46 bytes */
    _RAM_C2A0_                                           = 0xC2A0, /* 11 bytes */
    v_alex                                               = 0xC300, /* 32 bytes */
    v_entities                                           = 0xC300, /* 960 bytes */
    v_tempSprites                                        = 0xC700, /* 6 bytes */
    _RAM_C706_                                           = 0xC706,
    v_nametable                                          = 0xC800, /* 8 bytes */
    _RAM_C808_                                           = 0xC808,
    _RAM_C828_                                           = 0xC828, /* 36 bytes */
    _RAM_C850_                                           = 0xC850, /* 36 bytes */
    _RAM_C878_                                           = 0xC878, /* 36 bytes */
    _RAM_C908_                                           = 0xC908, /* 46 bytes */
    _RAM_CA08_                                           = 0xCA08, /* 36 bytes */
    _RAM_CA2C_                                           = 0xCA2C, /* 8 bytes */
    _RAM_CA94_                                           = 0xCA94,
    _RAM_CA9C_                                           = 0xCA9C,
    _RAM_CAA4_                                           = 0xCAA4,
    _RAM_CB08_                                           = 0xCB08, /* 8 bytes */
    _RAM_CBB4_                                           = 0xCBB4, /* 8 bytes */
    _RAM_CC06_                                           = 0xCC06,
    _RAM_CC08_                                           = 0xCC08,
    _RAM_CCD4_                                           = 0xCCD4,
    _RAM_CCD8_                                           = 0xCCD8,
    _RAM_CCDC_                                           = 0xCCDC,
    _RAM_CCE0_                                           = 0xCCE0,
    _RAM_CCE4_                                           = 0xCCE4,
    _RAM_CCE8_                                           = 0xCCE8,
    _RAM_CCEC_                                           = 0xCCEC,
    _RAM_CCF0_                                           = 0xCCF0,
    _RAM_CCF4_                                           = 0xCCF4, /* 4 bytes */
    _RAM_CCF8_                                           = 0xCCF8,
    _RAM_CD44_                                           = 0xCD44, /* 18 bytes */
    _RAM_CE84_                                           = 0xCE84,
    v_columnToDraw                                       = 0xCF00, /* 56 bytes */
    v_rowToDraw                                          = 0xCF38, /* 64 bytes */
    v_mapEntities                                        = 0xCF80, /* 96 bytes */
    v_textboxCursor                                      = 0xCFE0,
    v_nametableCopy                                      = 0xD000, /* 1283 bytes */
    _RAM_D503_                                           = 0xD503,
    _RAM_D504_                                           = 0xD504,
    _RAM_D506_                                           = 0xD506,
    v_decompressedLevelLayoutData                        = 0xD700,
    _RAM_D7D0_                                           = 0xD7D0,
    _RAM_D7D1_                                           = 0xD7D1,
    _RAM_D7DA_                                           = 0xD7DA,
    _RAM_D800_                                           = 0xD800,
    _RAM_D801_                                           = 0xD801,
    _RAM_D802_                                           = 0xD802,
    _RAM_D803_                                           = 0xD803,
    _RAM_D804_                                           = 0xD804,
    _RAM_D805_                                           = 0xD805,
    _RAM_D806_                                           = 0xD806,
    _RAM_D807_                                           = 0xD807,
    v_unknownEntityByteCount_RAM_D8A0_                   = 0xD8A0,
    v_metatileDeletesTable                               = 0xD900, /* 1536 bytes */
};

#endif
